# based on https://kubernetes.io/docs/tutorials/stateful-application/cassandra/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
   - name: cql
     port: 9042
     protocol: TCP
     targetPort: 9042
   - name: thrift
     port: 9160
     protocol: TCP
     targetPort: 9160
   - name: jmx
     port: 7199
     protocol: TCP
     targetPort: 7199
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        #image: gcr.io/google-samples/cassandra:v13
        # do not use this image in production, it is strictly
        # for proof of concept. JMX credentials are HARD CODED
        # in the image, this is NOT for production
        image: docker.io/bmedora/cassandra-k8s-bindplane
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: pure-intra
          protocol: TCP
        - containerPort: 7001
          name: tls-intra
          protocol: TCP
        - containerPort: 7199
          name: jmx
          protocol: TCP
        - containerPort: 9042
          name: cql
          protocol: TCP
        - containerPort: 9160
          name: thrift
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: LOCAL_JMX
            value: "no"
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "K8Demo"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # readinessProbe is disabled because it fails
        # when jmx auth is enabled!
        #readinessProbe:
        #  exec:
        #    command:
        #    - /bin/bash
        #    - -c
        #    - /ready-probe.sh
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tmp
        emptyDir: {}
      - name: downloadedplugins
        emptyDir: {}
      - name: log
        emptyDir: {}
      - name: jmx-password-volume
        configMap:
          name: jmx-password
      - name: jmx-access-volume
        configMap:
          name: jmx-access
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
